package application;

import javafx.fxml.FXML;
import javafx.fxml.FXMLLoader;
import javafx.fxml.Initializable;
import javafx.scene.Scene;
import javafx.scene.control.Alert;
import javafx.scene.control.Alert.AlertType;
import javafx.scene.control.Button;

import javafx.scene.control.TextField;
import javafx.scene.layout.Pane;
import javafx.stage.Stage;

import java.io.IOException;
import java.net.URL;
import java.util.ResourceBundle;

import javax.swing.JOptionPane;

import org.springframework.jdbc.core.JdbcTemplate;

import com.mysql.cj.jdbc.MysqlDataSource;

import javafx.collections.FXCollections;
import javafx.collections.ObservableList;
import javafx.event.ActionEvent;

import javafx.scene.control.ComboBox;

public class RegistrController implements Initializable{
	@FXML
	private Button nazad;
	@FXML
	private Button Reg;
	@FXML
	private TextField tx1;
	@FXML
	private TextField tx2;
	@FXML
	private TextField tx3;
	@FXML
	private TextField tx4;
	@FXML
	private TextField tx5;
	
	@FXML
	private TextField tx6;
	@FXML
	private ComboBox<String> cb1;

	MysqlDataSource dataSource;
	JdbcTemplate jb;
	ObservableList<String> statusValues = 
			FXCollections.observableArrayList("Админ","Пользователь");
	
	
	// Event Listener on Button[#nazad].onAction
	@FXML
	public void act_nazad(ActionEvent event) throws IOException {
		// TODO Autogenerated
		Pane root=null;
		root = (Pane)FXMLLoader.load(getClass().getResource("Vxod.fxml"));
		Stage stage = (Stage) nazad.getScene().getWindow();
		stage.setScene(new Scene(root,600,400));
	}
	// Event Listener on Button[#Reg].onAction
	@FXML
	public void act_reg(ActionEvent event) throws IOException {
		// TODO Autogenerated
		String ComboBoxs =  cb1.getValue();
		String ima = tx1.getText();
		String famil = tx2.getText();
		String otch = tx3.getText();
		String telefon = tx6.getText();
		String login_text = tx4.getText();
		String password_text = tx5.getText();
		
		jb = new JdbcTemplate(dataSource);
		// Проверка наличия логина в базе данных
		if (jb.queryForObject("SELECT COUNT(*) FROM user WHERE Login = ?", Integer.class, login_text) == 0) {
		    // Логин не существует, можно добавить новую запись
		    if (telefon.matches("[0-9]+")) {
		        if (ComboBoxs.equals("Админ")) {
		            String inputPassword = JOptionPane.showInputDialog(null, "Введите пароль для подтверждения");
		            // Далее можно добавить код для проверки пароля и выполнения операции только при правильном пароле
		            if (inputPassword.equals("Пароль админа")) {
		                // Пароль верный, выполнение операции
		                jb.update("insert into user(Ima,Famil,Otch,Telefon,Login,Parol,Roll) "
		                        + "values (?,?,?,?,?,?,?)",
		                        ima, famil, otch, telefon, login_text, password_text, ComboBoxs);
		            } else {
		                // Пароль неверный, вывод сообщения об ошибке
		                JOptionPane.showMessageDialog(null, "Неверный пароль. Операция отменена.");
		            }
		        } else { //для пользователя
		            jb.update("insert into user(Ima,Famil,Otch,Telefon,Login,Parol,Roll) "
		                    + "values (?,?,?,?,?,?,?)",
		                    ima, famil, otch, telefon, login_text, password_text, ComboBoxs);
		        }
		    } else {
		        Alert alert = new Alert(AlertType.INFORMATION);
		        alert.setTitle("Информация");
		        alert.setHeaderText(null);
		        alert.setContentText("Введите только цифры в номере телефона");
		        alert.showAndWait();
		    }
		} else {
		    // Логин уже существует, выведите сообщение об ошибке
		    Alert alert = new Alert(AlertType.ERROR);
		    alert.setTitle("Ошибка");
		    alert.setHeaderText(null);
		    alert.setContentText("Логин уже существует. Введите другой логин.");
		    alert.showAndWait();
		    tx4.clear();    
		}
		
		Alert alert2 = new Alert(AlertType.INFORMATION);
		alert2.setTitle("Ошибка");
		alert2.setHeaderText(null);
		alert2.setContentText("Вы зарегистрировались");
		alert2.showAndWait();
		Pane root=null;
		root = (Pane)FXMLLoader.load(getClass().getResource("Vxod.fxml"));
		Stage stage = (Stage) nazad.getScene().getWindow();
		stage.setScene(new Scene(root,600,400));
		
	}
	
	
	
	
	@Override
	public void initialize(URL arg0, ResourceBundle arg1) {
		// TODO Auto-generated method stub
		cb1.setItems(statusValues);
		tx1.clear();
		tx2.clear();
		tx3.clear();
		tx4.clear();
		tx5.clear();
		dataSource = new MysqlDataSource();
		dataSource.setServerName("localhost");
		dataSource.setPort(3306);
		dataSource.setDatabaseName("dem");
		dataSource.setUser("root");
		dataSource.setPassword("");
	}
}
