package application;

import javafx.fxml.FXML;
import javafx.fxml.FXMLLoader;
import javafx.fxml.Initializable;
import javafx.scene.Scene;
import javafx.scene.control.Alert;
import javafx.scene.control.Button;

import javafx.scene.control.TextField;
import javafx.scene.control.Alert.AlertType;
import javafx.scene.layout.Pane;
import javafx.stage.Stage;

import java.io.IOException;
import java.net.URL;
import java.util.ResourceBundle;

import org.springframework.jdbc.core.JdbcTemplate;

import com.mysql.cj.jdbc.MysqlDataSource;

import javafx.event.ActionEvent;

import javafx.scene.control.PasswordField;

public class VxodController implements Initializable{
	@FXML
	private TextField tx1;
	@FXML
	private Button reg;
	@FXML
	private Button vxod;
	@FXML
	private PasswordField tx2;
	
	
	MysqlDataSource dataSource;
	JdbcTemplate jb;

	// Event Listener on Button[#reg].onAction
	@FXML
	public void act_reg(ActionEvent event) throws IOException {
		// TODO Autogenerated
		Pane root=null;
		root = (Pane)FXMLLoader.load(getClass().getResource("Registr.fxml"));
		Stage stage = (Stage) reg.getScene().getWindow();
		stage.setScene(new Scene(root,500,400));
	}
	
	// Event Listener on Button[#vxod].onAction
	@FXML
	public void act_vxod(ActionEvent event) throws IOException {
		// TODO Autogenerated
		
		String login2 =tx1.getText();
		String parol2 = tx2.getText();
		
		if (login2.isEmpty()|parol2.isEmpty()) 
		{
			Alert alert = new Alert(AlertType.INFORMATION);
			alert.setContentText("Логин и Пароль не может быть пустым ");
			alert.showAndWait();
		}
		else {
			jb = new JdbcTemplate(dataSource);
			var rez =  jb.query("Select Parol from user where Login='"+login2+"'", 
					(resultSet, rowNum) -> {return resultSet.getString("Parol");});
			var rez2 =  jb.query("Select Roll from user where Login='"+login2+"'", 
					(resultSet, rowNum) -> {return resultSet.getString("Roll");});
			
			if (rez.size()>0 && rez.get(0).equals(parol2) && rez2.size()>0 && rez2.get(0).equals("Админ")) {
				FXMLLoader loader = new FXMLLoader(getClass().getResource("Ocno_admin.fxml"));
			    Pane root = (Pane) loader.load();
			    // Получаем контроллер новой формы
			    Ocno_adminController controller = loader.getController();
			    controller.setCurrentUser(login2); 
			    Stage stage = (Stage) reg.getScene().getWindow();
			    stage.setScene(new Scene(root, 1200, 700));
				
			}else if(rez.size()>0 && rez.get(0).equals(parol2) && rez2.size()>0 && rez2.get(0).equals("Пользователь")){
				FXMLLoader loader = new FXMLLoader(getClass().getResource("Okno_pervoe.fxml"));
			    Pane root = (Pane) loader.load();
			    // Получаем контроллер новой формы
			    Okno_pervoeController controller = loader.getController();
			    controller.setCurrentUser(login2); 
			    Stage stage = (Stage) reg.getScene().getWindow();
			    stage.setScene(new Scene(root, 1100, 700));
		
			}else {
				Alert alert = new Alert(AlertType.ERROR);
				alert.setContentText("Неверный логин или пароль");
				alert.showAndWait();
			}
		}
		
	}
	@Override
	public void initialize(URL arg0, ResourceBundle arg1) {
		// TODO Auto-generated method stub
		tx1.clear();
		tx2.clear();
		dataSource = new MysqlDataSource();
		dataSource.setServerName("localhost");
		dataSource.setPort(3306);
		dataSource.setDatabaseName("dem");
		dataSource.setUser("root");
		dataSource.setPassword("");
	}
}
